// ─────────────────────────────────────────────────────────────
// 순례(巡禮) — 불교 일정과 전국의 이름난 도량.
// · 일정: korean-lunar-calendar(순수 JS, 키·서버 불필요)로
//   음력→양력을 해마다 자동 계산한다.
//   검증 — 부처님오신날(음 4/8): 2025-05-05 · 2026-05-24 공지 값과 일치.
// · 도량: 정적 자료. 길찾기는 카카오맵 '이름 검색' 링크로 간다 —
//   API 키가 필요 없는 공식 링크 방식.
// ─────────────────────────────────────────────────────────────

import KoreanLunarCalendar from "korean-lunar-calendar";

// ── 불교 일정 ──────────────────────────────────────────────

export type PilgrimEvent = {
  name: string;
  hanja: string;
  note: string; // 한 줄
  date: Date; // 양력, 그날 0시
  dDay: number; // 0 = 오늘
  major: boolean; // 큰 날 — 금색 강조
};

// 해마다 오는 날 — 음력 월·일로 적어 두면 양력은 계산이 맡는다
const ANNUAL: {
  name: string;
  hanja: string;
  note: string;
  month: number;
  day: number;
  major: boolean;
}[] = [
  {
    name: "동안거 해제",
    hanja: "冬安居 解制",
    note: "석 달 겨울 정진을 마치고 산문을 나서는 날.",
    month: 1,
    day: 15,
    major: false,
  },
  {
    name: "출가재일",
    hanja: "出家齋日",
    note: "태자 싯다르타가 성을 나서 길 위에 선 날.",
    month: 2,
    day: 8,
    major: true,
  },
  {
    name: "열반재일",
    hanja: "涅槃齋日",
    note: "부처님께서 사라쌍수 아래 열반에 드신 날.",
    month: 2,
    day: 15,
    major: true,
  },
  {
    name: "부처님오신날",
    hanja: "佛誕日",
    note: "온 산문에 연등이 걸리는 날.",
    month: 4,
    day: 8,
    major: true,
  },
  {
    name: "하안거 결제",
    hanja: "夏安居 結制",
    note: "여름 석 달, 산문을 닫고 정진에 드는 날.",
    month: 4,
    day: 15,
    major: false,
  },
  {
    name: "우란분절 · 백중",
    hanja: "盂蘭盆節",
    note: "먼저 간 이들을 위해 재를 올리는 날.",
    month: 7,
    day: 15,
    major: true,
  },
  {
    name: "하안거 해제",
    hanja: "夏安居 解制",
    note: "여름 정진을 마치고 만행을 떠나는 날.",
    month: 7,
    day: 15,
    major: false,
  },
  {
    name: "동안거 결제",
    hanja: "冬安居 結制",
    note: "겨울 석 달, 문을 닫고 정진에 드는 날.",
    month: 10,
    day: 15,
    major: false,
  },
  {
    name: "성도재일",
    hanja: "成道齋日",
    note: "새벽 별을 보고 크게 깨달으신 날.",
    month: 12,
    day: 8,
    major: true,
  },
];

// 다달이 오는 재일 — 음력 날짜만 정해져 있다
const MONTHLY: { name: string; hanja: string; note: string; day: number }[] = [
  {
    name: "지장재일",
    hanja: "地藏齋日",
    note: "지장보살을 생각하며 하루 계를 지키는 날.",
    day: 18,
  },
  {
    name: "관음재일",
    hanja: "觀音齋日",
    note: "관세음보살을 부르며 마음을 씻는 날.",
    day: 24,
  },
];

// 음력 → 양력. 없는 날(작은달 30일 등)이면 null.
export function lunarToSolar(
  lunarYear: number,
  lunarMonth: number,
  lunarDay: number,
  intercalation = false
): Date | null {
  const cal = new KoreanLunarCalendar();
  if (!cal.setLunarDate(lunarYear, lunarMonth, lunarDay, intercalation)) {
    return null;
  }
  const s = cal.getSolarCalendar();
  return new Date(s.year, s.month - 1, s.day);
}

const DAY_MS = 24 * 60 * 60 * 1000;

// 오늘부터 다가오는 순으로 count개.
// 음력 12월은 양력으로 이듬해 1월에 떨어지므로,
// 지난해·올해·이듬해 세 음력 해를 훑어 연 경계를 넘긴다.
// 윤달: 큰 명절은 평달로 지내고(intercalation=false),
// 다달이 재일은 윤달에도 달이 뜨므로 윤달 날짜도 함께 살핀다.
export function upcomingEvents(count: number, base: Date = new Date()): PilgrimEvent[] {
  const today = new Date(base.getFullYear(), base.getMonth(), base.getDate());
  const out: PilgrimEvent[] = [];

  const push = (
    name: string,
    hanja: string,
    note: string,
    date: Date | null,
    major: boolean
  ) => {
    if (!date) return;
    const dDay = Math.round((date.getTime() - today.getTime()) / DAY_MS);
    if (dDay < 0) return;
    out.push({ name, hanja, note, date, dDay, major });
  };

  for (let ly = today.getFullYear() - 1; ly <= today.getFullYear() + 1; ly++) {
    for (const e of ANNUAL) {
      push(e.name, e.hanja, e.note, lunarToSolar(ly, e.month, e.day), e.major);
    }
    for (let m = 1; m <= 12; m++) {
      for (const e of MONTHLY) {
        push(e.name, e.hanja, e.note, lunarToSolar(ly, m, e.day), false);
        push(e.name, e.hanja, e.note, lunarToSolar(ly, m, e.day, true), false);
      }
    }
  }

  // 가까운 날부터 — 같은 날이면 큰 날을 앞에
  out.sort(
    (a, b) =>
      a.date.getTime() - b.date.getTime() || Number(b.major) - Number(a.major)
  );
  return out.slice(0, count);
}

// ── 전국의 이름난 도량 ─────────────────────────────────────

export type Region = "수도권" | "강원" | "충청" | "영남" | "호남" | "제주";

export const REGIONS: Region[] = [
  "수도권",
  "강원",
  "충청",
  "영남",
  "호남",
  "제주",
];

export type Temple = {
  name: string;
  hanja?: string;
  mountain: string; // 산문 — 절이 깃든 산
  region: Region;
  address: string;
  note: string; // 한 줄 — 담백하게
  lat: number; // 지도 마커용 — 아는 곳은 소수 3~4자리로 다듬었다.
  lng: number; // 확신 없는 몇 곳은 대략값 그대로 · 길찾기는 이름 검색으로 간다
  templestay?: boolean; // 템플스테이 운영 절 — 지도 필터·마커 점·팝업 배지용
  homepage?: string; // 공식 홈페이지 — 있는 절만 팝업에 [홈페이지 →]로 잇는다
};

export const TEMPLES: Temple[] = [
  // ── 수도권 ──
  {
    name: "조계사",
    hanja: "曹溪寺",
    mountain: "총본산",
    region: "수도권",
    address: "서울 종로구 우정국로 55",
    note: "도심 한복판, 대한불교조계종의 총본산.",
    lat: 37.5738,
    lng: 126.9818,
    templestay: true,
  },
  {
    name: "봉은사",
    hanja: "奉恩寺",
    mountain: "수도산",
    region: "수도권",
    address: "서울 강남구 봉은사로 531",
    note: "빌딩 숲 곁에 앉은 천년 도량.",
    lat: 37.5146,
    lng: 127.0576,
    templestay: true,
  },
  {
    name: "화계사",
    hanja: "華溪寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울 강북구 화계사길 117",
    note: "삼각산 자락, 국제 선원이 깃든 참선 도량.",
    lat: 37.6335,
    lng: 127.0175,
    templestay: true,
  },
  {
    name: "도선사",
    hanja: "道詵寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울 강북구 삼양로173길 504",
    note: "도선 국사가 터를 잡은 북한산 기도 도량.",
    lat: 37.6559,
    lng: 126.9926,
  },
  {
    name: "봉선사",
    hanja: "奉先寺",
    mountain: "운악산",
    region: "수도권",
    address: "경기 남양주시 진접읍 봉선사길 32",
    note: "한글 경전 번역의 산실이 된 운악산 본찰.",
    lat: 37.7589,
    lng: 127.1858,
    templestay: true,
  },
  {
    name: "용주사",
    hanja: "龍珠寺",
    mountain: "화산",
    region: "수도권",
    address: "경기 화성시 용주로 136",
    note: "정조가 아버지를 기리며 세운 효행의 절.",
    lat: 37.2109,
    lng: 126.9963,
    templestay: true,
  },
  {
    name: "전등사",
    hanja: "傳燈寺",
    mountain: "정족산",
    region: "수도권",
    address: "인천 강화군 길상면 전등사로 37-41",
    note: "삼랑성 안에 깃든 강화의 오랜 도량.",
    lat: 37.6314,
    lng: 126.4854,
    templestay: true,
  },
  {
    name: "보문사",
    hanja: "普門寺",
    mountain: "낙가산",
    region: "수도권",
    address: "인천 강화군 삼산면 삼산남로828번길 44",
    note: "석모도 눈썹바위 아래 마애관음의 기도처.",
    lat: 37.688,
    lng: 126.307,
  },
  {
    name: "진관사",
    hanja: "津寬寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울 은평구 진관길 73",
    note: "사찰음식으로 이름난 북한산 자락의 비구니 도량.",
    lat: 37.6385,
    lng: 126.945,
    templestay: true,
  },
  {
    name: "금선사",
    hanja: "金仙寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울 종로구 비봉길 137",
    note: "북한산 비봉 아래, 목정굴 관음 기도처.",
    lat: 37.617,
    lng: 126.955,
    templestay: true,
  },
  {
    name: "길상사",
    hanja: "吉祥寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울 성북구 선잠로5길 68",
    note: "법정 스님의 무소유가 깃든 성북동 도량.",
    lat: 37.6005,
    lng: 126.9965,
  },
  {
    name: "봉원사",
    hanja: "奉元寺",
    mountain: "안산",
    region: "수도권",
    address: "서울 서대문구 봉원사길 120",
    note: "영산재를 전승해 온 태고종 총본산.",
    lat: 37.5745,
    lng: 126.934,
  },
  {
    name: "수종사",
    hanja: "水鐘寺",
    mountain: "운길산",
    region: "수도권",
    address: "경기 남양주시 조안면 북한강로433번길 186",
    note: "두물머리가 한눈에 드는 운길산 중턱의 절.",
    lat: 37.5662,
    lng: 127.3055,
  },
  {
    name: "신륵사",
    hanja: "神勒寺",
    mountain: "봉미산",
    region: "수도권",
    address: "경기 여주시 신륵사길 73",
    note: "남한강 물가에 앉은 보기 드문 강가의 절.",
    lat: 37.299,
    lng: 127.653,
    templestay: true,
  },
  {
    name: "연주암",
    hanja: "戀主庵",
    mountain: "관악산",
    region: "수도권",
    address: "경기 과천시 자하동길 63",
    note: "관악산 마루 아래, 연주대를 이고 앉은 암자.",
    lat: 37.4425,
    lng: 126.966,
  },
  {
    name: "망월사",
    hanja: "望月寺",
    mountain: "도봉산",
    region: "수도권",
    address: "경기 의정부시 망월로28번길 211",
    note: "도봉산 포대능선 아래 달을 바라보는 절.",
    lat: 37.716,
    lng: 127.025,
  },
  {
    name: "용문사",
    hanja: "龍門寺",
    mountain: "용문산",
    region: "수도권",
    address: "경기 양평군 용문면 용문산로 782",
    note: "천년 은행나무가 산문을 지키는 절.",
    lat: 37.541,
    lng: 127.577,
    templestay: true,
  },
  {
    name: "봉녕사",
    hanja: "奉寧寺",
    mountain: "광교산",
    region: "수도권",
    address: "경기 수원시 팔달구 창룡대로 236-54",
    note: "사찰음식을 가르쳐 온 비구니 승가대학의 절.",
    lat: 37.294,
    lng: 127.033,
  },
  // ── 강원 ──
  {
    name: "월정사",
    hanja: "月精寺",
    mountain: "오대산",
    region: "강원",
    address: "강원 평창군 진부면 오대산로 374-8",
    note: "전나무 숲길 끝에 앉은 오대산 본찰.",
    lat: 37.7317,
    lng: 128.5926,
    templestay: true,
  },
  {
    name: "상원사",
    hanja: "上院寺",
    mountain: "오대산",
    region: "강원",
    address: "강원 평창군 진부면 오대산로 1211-50",
    note: "가장 오래된 동종이 아침을 여는 절.",
    lat: 37.7788,
    lng: 128.5636,
  },
  {
    name: "낙산사",
    hanja: "洛山寺",
    mountain: "오봉산",
    region: "강원",
    address: "강원 양양군 강현면 낙산사로 100",
    note: "동해를 굽어보는 해수관음의 절.",
    lat: 38.1247,
    lng: 128.6277,
    templestay: true,
  },
  {
    name: "신흥사",
    hanja: "新興寺",
    mountain: "설악산",
    region: "강원",
    address: "강원 속초시 설악산로 1137",
    note: "설악으로 드는 산문 — 통일대불이 맞이한다.",
    lat: 38.164,
    lng: 128.477,
    templestay: true,
  },
  {
    name: "백담사",
    hanja: "百潭寺",
    mountain: "설악산",
    region: "강원",
    address: "강원 인제군 북면 백담로 746",
    note: "만해 한용운이 머물던 내설악의 절.",
    lat: 38.1653,
    lng: 128.3733,
    templestay: true,
  },
  {
    name: "봉정암",
    hanja: "鳳頂庵",
    mountain: "설악산",
    region: "강원",
    address: "강원 인제군 북면 백담로 1700",
    note: "설악 가장 높은 곳, 진신사리를 모신 기도처.",
    lat: 38.132,
    lng: 128.444,
  },
  {
    name: "청평사",
    hanja: "淸平寺",
    mountain: "오봉산",
    region: "강원",
    address: "강원 춘천시 북산면 오봉산길 810",
    note: "배로 소양호를 건너 닿는 오봉산 고찰.",
    lat: 37.9795,
    lng: 127.7975,
  },
  {
    name: "구룡사",
    hanja: "龜龍寺",
    mountain: "치악산",
    region: "강원",
    address: "강원 원주시 소초면 구룡사로 500",
    note: "아홉 용의 전설이 깃든 치악산 들머리 고찰.",
    lat: 37.3997,
    lng: 128.0497,
    templestay: true,
  },
  {
    name: "삼화사",
    hanja: "三和寺",
    mountain: "두타산",
    region: "강원",
    address: "강원 동해시 삼화로 584",
    note: "무릉계곡 들머리, 국행수륙재를 지내는 절.",
    lat: 37.468,
    lng: 129.009,
    templestay: true,
  },
  {
    name: "법흥사",
    hanja: "法興寺",
    mountain: "사자산",
    region: "강원",
    address: "강원 영월군 무릉도원면 무릉법흥로 1352",
    note: "진신사리를 모신 사자산 적멸보궁.",
    lat: 37.373,
    lng: 128.277,
    templestay: true,
  },
  {
    name: "정암사",
    hanja: "淨巖寺",
    mountain: "태백산",
    region: "강원",
    address: "강원 정선군 고한읍 함백산로 1410",
    note: "국보 수마노탑에 사리를 모신 높은 골짜기의 보궁.",
    lat: 37.183,
    lng: 128.8927,
  },
  {
    name: "건봉사",
    hanja: "乾鳳寺",
    mountain: "금강산",
    region: "강원",
    address: "강원 고성군 거진읍 건봉사로 723",
    note: "휴전선 가까이 남은 금강산 자락의 옛 대가람.",
    lat: 38.403,
    lng: 128.3786,
    templestay: true,
  },
  // ── 충청 ──
  {
    name: "수덕사",
    hanja: "修德寺",
    mountain: "덕숭산",
    region: "충청",
    address: "충남 예산군 덕산면 수덕사안길 79",
    note: "고려 대웅전이 남아 있는 선지종찰.",
    lat: 36.6623,
    lng: 126.6216,
    templestay: true,
  },
  {
    name: "마곡사",
    hanja: "麻谷寺",
    mountain: "태화산",
    region: "충청",
    address: "충남 공주시 사곡면 마곡사로 966",
    note: "봄 마곡 — 태화산 물돌이에 앉은 절.",
    lat: 36.5565,
    lng: 127.0083,
    templestay: true,
  },
  {
    name: "법주사",
    hanja: "法住寺",
    mountain: "속리산",
    region: "충청",
    address: "충북 보은군 속리산면 법주사로 405",
    note: "하나뿐인 목탑 팔상전이 서 있는 절.",
    lat: 36.5417,
    lng: 127.8332,
    templestay: true,
  },
  {
    name: "갑사",
    hanja: "甲寺",
    mountain: "계룡산",
    region: "충청",
    address: "충남 공주시 계룡면 갑사로 567-3",
    note: "가을 갑사 — 계룡산 서쪽 기슭의 고찰.",
    lat: 36.3482,
    lng: 127.197,
    templestay: true,
  },
  {
    name: "동학사",
    hanja: "東鶴寺",
    mountain: "계룡산",
    region: "충청",
    address: "충남 공주시 반포면 동학사1로 462",
    note: "계룡산 동쪽 골짜기의 비구니 강원.",
    lat: 36.344,
    lng: 127.25,
  },
  {
    name: "구인사",
    hanja: "救仁寺",
    mountain: "소백산",
    region: "충청",
    address: "충북 단양군 영춘면 구인사길 73",
    note: "소백산 골짜기를 따라 오르는 천태종 총본산.",
    lat: 37.043,
    lng: 128.541,
    templestay: true,
  },
  {
    name: "관촉사",
    hanja: "灌燭寺",
    mountain: "반야산",
    region: "충청",
    address: "충남 논산시 관촉로1번길 25",
    note: "은진미륵이 천 년을 서 있는 절.",
    lat: 36.187,
    lng: 127.106,
  },
  {
    name: "무량사",
    hanja: "無量寺",
    mountain: "만수산",
    region: "충청",
    address: "충남 부여군 외산면 무량로 203",
    note: "매월당 김시습이 생을 마친 만수산 고찰.",
    lat: 36.3171,
    lng: 126.6929,
  },
  {
    name: "개심사",
    hanja: "開心寺",
    mountain: "상왕산",
    region: "충청",
    address: "충남 서산시 운산면 개심사로 321-86",
    note: "휜 나무를 그대로 기둥 삼은 상왕산 고찰.",
    lat: 36.7469,
    lng: 126.5904,
  },
  {
    name: "신원사",
    hanja: "新元寺",
    mountain: "계룡산",
    region: "충청",
    address: "충남 공주시 계룡면 신원사동길 1",
    note: "계룡산 산신께 제를 올리던 중악단이 있는 절.",
    lat: 36.3354,
    lng: 127.1842,
  },
  {
    name: "장곡사",
    hanja: "長谷寺",
    mountain: "칠갑산",
    region: "충청",
    address: "충남 청양군 대치면 장곡길 241",
    note: "대웅전이 위아래로 둘 있는 칠갑산 고찰.",
    lat: 36.4174,
    lng: 126.8599,
  },
  // ── 영남 ──
  {
    name: "통도사",
    hanja: "通度寺",
    mountain: "영축산",
    region: "영남",
    address: "경남 양산시 하북면 통도사로 108",
    note: "진신사리를 모신 불보사찰 — 대웅전에 불상이 없다.",
    lat: 35.488,
    lng: 129.0641,
    templestay: true,
  },
  {
    name: "해인사",
    hanja: "海印寺",
    mountain: "가야산",
    region: "영남",
    address: "경남 합천군 가야면 해인사길 122",
    note: "팔만대장경을 지켜온 법보사찰.",
    lat: 35.8011,
    lng: 128.0978,
    templestay: true,
  },
  {
    name: "불국사",
    hanja: "佛國寺",
    mountain: "토함산",
    region: "영남",
    address: "경북 경주시 불국로 385",
    note: "석가탑과 다보탑이 마주 선 토함산 대가람.",
    lat: 35.79,
    lng: 129.3322,
    templestay: true,
  },
  {
    name: "석굴암",
    hanja: "石窟庵",
    mountain: "토함산",
    region: "영남",
    address: "경북 경주시 석굴로 238",
    note: "동해를 바라보는 돌집 안의 본존불.",
    lat: 35.795,
    lng: 129.3492,
  },
  {
    name: "범어사",
    hanja: "梵魚寺",
    mountain: "금정산",
    region: "영남",
    address: "부산 금정구 범어사로 250",
    note: "금정산 자락의 영남 선찰대본산.",
    lat: 35.2839,
    lng: 129.0683,
    templestay: true,
  },
  {
    name: "동화사",
    hanja: "桐華寺",
    mountain: "팔공산",
    region: "영남",
    address: "대구 동구 동화사1길 1",
    note: "팔공산 약사여래대불의 기도 도량.",
    lat: 35.9924,
    lng: 128.7008,
    templestay: true,
  },
  {
    name: "은해사",
    hanja: "銀海寺",
    mountain: "팔공산",
    region: "영남",
    address: "경북 영천시 청통면 청통로 951",
    note: "안개가 은빛 바다를 이룬다는 이름의 절.",
    lat: 36.008,
    lng: 128.759,
    templestay: true,
  },
  {
    name: "직지사",
    hanja: "直指寺",
    mountain: "황악산",
    region: "영남",
    address: "경북 김천시 대항면 직지사길 95",
    note: "직지인심 — 마음을 곧바로 가리키는 이름의 절.",
    lat: 36.119,
    lng: 128.002,
    templestay: true,
  },
  {
    name: "부석사",
    hanja: "浮石寺",
    mountain: "봉황산",
    region: "영남",
    address: "경북 영주시 부석면 부석사로 345",
    note: "무량수전 배흘림기둥에 노을이 드는 절.",
    lat: 36.9988,
    lng: 128.6869,
    templestay: true,
  },
  {
    name: "쌍계사",
    hanja: "雙磎寺",
    mountain: "지리산",
    region: "영남",
    address: "경남 하동군 화개면 쌍계사길 59",
    note: "화개 골짜기, 차와 범패의 절.",
    lat: 35.2339,
    lng: 127.645,
    templestay: true,
  },
  {
    name: "표충사",
    hanja: "表忠寺",
    mountain: "재약산",
    region: "영남",
    address: "경남 밀양시 단장면 표충로 1338",
    note: "사명대사의 충절을 함께 모신 절.",
    lat: 35.496,
    lng: 128.866,
    templestay: true,
  },
  {
    name: "봉정사",
    hanja: "鳳停寺",
    mountain: "천등산",
    region: "영남",
    address: "경북 안동시 서후면 봉정사길 222",
    note: "가장 오래된 목조건물 극락전이 남은 절.",
    lat: 36.646,
    lng: 128.648,
    templestay: true,
  },
  {
    name: "고운사",
    hanja: "孤雲寺",
    mountain: "등운산",
    region: "영남",
    address: "경북 의성군 단촌면 고운사길 415",
    note: "고운 최치원의 자취가 깃든 등운산 본찰.",
    lat: 36.4581,
    lng: 128.7496,
  },
  {
    name: "봉암사",
    hanja: "鳳巖寺",
    mountain: "희양산",
    region: "영남",
    address: "경북 문경시 가은읍 원북길 313",
    note: "부처님오신날 하루만 산문을 여는 참선 종가.",
    lat: 36.6998,
    lng: 128.0081,
  },
  {
    name: "운문사",
    hanja: "雲門寺",
    mountain: "호거산",
    region: "영남",
    address: "경북 청도군 운문면 운문사길 264",
    note: "솔바람 길 끝의 비구니 승가대학 도량.",
    lat: 35.667,
    lng: 128.967,
  },
  {
    name: "기림사",
    hanja: "祇林寺",
    mountain: "함월산",
    region: "영남",
    address: "경북 경주시 문무대왕면 기림로 437-17",
    note: "다섯 가지 물맛으로 이름난 함월산 옛 절.",
    lat: 35.8375,
    lng: 129.4031,
  },
  {
    name: "골굴사",
    hanja: "骨窟寺",
    mountain: "함월산",
    region: "영남",
    address: "경북 경주시 문무대왕면 기림로 101-5",
    note: "석굴 법당과 선무도로 이름난 절.",
    lat: 35.792,
    lng: 129.406,
    templestay: true,
  },
  {
    name: "석남사",
    hanja: "石南寺",
    mountain: "가지산",
    region: "영남",
    address: "울산 울주군 상북면 석남로 557",
    note: "가지산 계곡 곁의 비구니 참선 도량.",
    lat: 35.6215,
    lng: 129.0327,
  },
  {
    name: "보리암",
    hanja: "菩提庵",
    mountain: "금산",
    region: "영남",
    address: "경남 남해군 상주면 보리암로 665",
    note: "남해 금산 바위 끝에 앉은 해수관음 기도처.",
    lat: 34.7425,
    lng: 127.9825,
  },
  // ── 호남 ──
  {
    name: "송광사",
    hanja: "松廣寺",
    mountain: "조계산",
    region: "호남",
    address: "전남 순천시 송광면 송광사안길 100",
    note: "열여섯 국사를 배출한 승보사찰.",
    lat: 34.9952,
    lng: 127.2748,
    templestay: true,
  },
  {
    name: "선암사",
    hanja: "仙巖寺",
    mountain: "조계산",
    region: "호남",
    address: "전남 순천시 승주읍 선암사길 450",
    note: "승선교 무지개다리 너머의 옛 절.",
    lat: 34.9967,
    lng: 127.3311,
    templestay: true,
  },
  {
    name: "화엄사",
    hanja: "華嚴寺",
    mountain: "지리산",
    region: "호남",
    address: "전남 구례군 마산면 화엄사로 539",
    note: "각황전이 우뚝한 지리산 화엄의 본찰.",
    lat: 35.2573,
    lng: 127.4991,
    templestay: true,
  },
  {
    name: "대흥사",
    hanja: "大興寺",
    mountain: "두륜산",
    region: "호남",
    address: "전남 해남군 삼산면 대흥사길 400",
    note: "서산대사의 의발이 전해 온 두륜산 대도량.",
    lat: 34.478,
    lng: 126.615,
    templestay: true,
  },
  {
    name: "미황사",
    hanja: "美黃寺",
    mountain: "달마산",
    region: "호남",
    address: "전남 해남군 송지면 미황사길 164",
    note: "달마산 바위 병풍 아래 남녘 끝 절.",
    lat: 34.41,
    lng: 126.594,
    templestay: true,
  },
  {
    name: "백양사",
    hanja: "白羊寺",
    mountain: "백암산",
    region: "호남",
    address: "전남 장성군 북하면 백양로 1239",
    note: "흰 바위와 애기단풍의 고불총림.",
    lat: 35.437,
    lng: 126.855,
    templestay: true,
  },
  {
    name: "내장사",
    hanja: "內藏寺",
    mountain: "내장산",
    region: "호남",
    address: "전북 정읍시 내장산로 1253",
    note: "단풍 골짜기 가장 안쪽에 앉은 절.",
    lat: 35.484,
    lng: 126.89,
  },
  {
    name: "금산사",
    hanja: "金山寺",
    mountain: "모악산",
    region: "호남",
    address: "전북 김제시 금산면 모악15길 1",
    note: "삼층 미륵전이 서 있는 미륵신앙의 본향.",
    lat: 35.718,
    lng: 127.049,
    templestay: true,
  },
  {
    name: "선운사",
    hanja: "禪雲寺",
    mountain: "도솔산",
    region: "호남",
    address: "전북 고창군 아산면 선운사로 250",
    note: "동백숲과 꽃무릇으로 이름난 고찰.",
    lat: 35.4974,
    lng: 126.5801,
    templestay: true,
  },
  {
    name: "향일암",
    hanja: "向日庵",
    mountain: "금오산",
    region: "호남",
    address: "전남 여수시 돌산읍 향일암로 60",
    note: "해 뜨는 바다를 마주한 남해 기도처.",
    lat: 34.5936,
    lng: 127.8032,
  },
  {
    name: "내소사",
    hanja: "來蘇寺",
    mountain: "능가산",
    region: "호남",
    address: "전북 부안군 진서면 내소사로 243",
    note: "전나무 숲길과 꽃살문 대웅보전의 절.",
    lat: 35.6175,
    lng: 126.586,
    templestay: true,
  },
  {
    name: "실상사",
    hanja: "實相寺",
    mountain: "지리산",
    region: "호남",
    address: "전북 남원시 산내면 입석길 94-129",
    note: "지리산 들녘에 낮게 앉은 구산선문 첫 가람.",
    lat: 35.423,
    lng: 127.635,
    templestay: true,
  },
  {
    name: "천은사",
    hanja: "泉隱寺",
    mountain: "지리산",
    region: "호남",
    address: "전남 구례군 광의면 노고단로 209",
    note: "샘이 숨었다는 이름의 지리산 서쪽 산문.",
    lat: 35.271,
    lng: 127.461,
  },
  {
    name: "운주사",
    hanja: "雲住寺",
    mountain: "천불산",
    region: "호남",
    address: "전남 화순군 도암면 천태로 91-44",
    note: "와불이 누워 있는 천불천탑의 절.",
    lat: 34.918,
    lng: 126.8895,
  },
  {
    name: "무위사",
    hanja: "無爲寺",
    mountain: "월출산",
    region: "호남",
    address: "전남 강진군 성전면 무위사로 308",
    note: "국보 극락보전이 남아 있는 월출산 남쪽 고찰.",
    lat: 34.7435,
    lng: 126.687,
  },
  {
    name: "도갑사",
    hanja: "道岬寺",
    mountain: "월출산",
    region: "호남",
    address: "전남 영암군 군서면 도갑사로 306",
    note: "월출산 서쪽 기슭, 도선 국사의 옛 터.",
    lat: 34.7522,
    lng: 126.6628,
  },
  {
    name: "불갑사",
    hanja: "佛甲寺",
    mountain: "불갑산",
    region: "호남",
    address: "전남 영광군 불갑면 불갑사로 450",
    note: "가을이면 꽃무릇이 온 산을 물들이는 절.",
    lat: 35.193,
    lng: 126.562,
  },
  // ── 제주 ──
  {
    name: "관음사",
    hanja: "觀音寺",
    mountain: "한라산",
    region: "제주",
    address: "제주 제주시 산록북로 660",
    note: "한라산 기슭, 제주 불교의 본산.",
    lat: 33.4257,
    lng: 126.5566,
    templestay: true,
  },
  {
    name: "약천사",
    hanja: "藥泉寺",
    mountain: "한라산",
    region: "제주",
    address: "제주 서귀포시 이어도로 293-28",
    note: "바다를 앞에 둔 큰 법당의 절.",
    lat: 33.246,
    lng: 126.489,
    templestay: true,
  },
  {
    name: "법화사",
    hanja: "法華寺",
    mountain: "한라산",
    region: "제주",
    address: "제주 서귀포시 하원북로35번길 15-1",
    note: "장보고의 전설이 전하는 제주의 옛 절.",
    lat: 33.2646,
    lng: 126.4575,
  },
  {
    name: "산방굴사",
    hanja: "山房窟寺",
    mountain: "산방산",
    region: "제주",
    address: "제주 서귀포시 안덕면 산방로 218-10",
    note: "산방산 바위굴에서 바다를 내려다보는 기도처.",
    lat: 33.2379,
    lng: 126.3131,
  },
  // ── 수도권 · 2차 보강 ──
  {
    name: "흥천사",
    hanja: "興天寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울특별시 성북구 흥천사길 29",
    note: "태조가 먼저 떠난 왕비를 그리며 세운 왕실의 원찰.",
    lat: 37.5982,
    lng: 127.0092,
  },
  {
    name: "경국사",
    hanja: "慶國寺",
    mountain: "삼각산",
    region: "수도권",
    address: "서울특별시 성북구 보국문로 113-10",
    note: "정릉 골짜기 물소리 따라 오르면 만나는 보물 목각탱의 절.",
    lat: 37.6147,
    lng: 127.0046,
    templestay: true,
  },
  {
    name: "승가사",
    hanja: "僧伽寺",
    mountain: "북한산",
    region: "수도권",
    address: "서울특별시 종로구 비봉4길 213",
    note: "비봉 아래 바위에 새긴 마애불이 서울을 굽어보는 절.",
    lat: 37.6266,
    lng: 126.9604,
  },
  {
    name: "삼막사",
    hanja: "三幕寺",
    mountain: "삼성산",
    region: "수도권",
    address: "경기도 안양시 만안구 삼막로 478",
    note: "원효와 의상이 막을 치고 수행하던 삼성산 중턱의 옛 절.",
    lat: 37.4346,
    lng: 126.9362,
  },
  {
    name: "청계사",
    hanja: "淸溪寺",
    mountain: "청계산",
    region: "수도권",
    address: "경기도 의왕시 청계로 475",
    note: "우담바라 전설을 간직한 청계산 자락의 고요한 절.",
    lat: 37.4109,
    lng: 127.0353,
    templestay: true,
  },
  {
    name: "자재암",
    hanja: "自在庵",
    mountain: "소요산",
    region: "수도권",
    address: "경기도 동두천시 평화로2910번길 406-33",
    note: "원효가 흐르는 물에 마음을 씻던 소요산 폭포 곁 암자.",
    lat: 37.9456,
    lng: 127.0864,
  },
  {
    name: "칠장사",
    hanja: "七長寺",
    mountain: "칠현산",
    region: "수도권",
    address: "경기도 안성시 죽산면 칠장로 399-18",
    note: "일곱 도적이 현인이 되었다는 전설이 서린 천년 고찰.",
    lat: 37.0263,
    lng: 127.3971,
  },
  {
    name: "현등사",
    hanja: "懸燈寺",
    mountain: "운악산",
    region: "수도권",
    address: "경기도 가평군 조종면 현등사길 34",
    note: "옥등의 불빛이 이끈 자리, 운악산 벼랑에 걸린 절.",
    lat: 37.8706,
    lng: 127.331,
  },
  {
    name: "보광사",
    hanja: "普光寺",
    mountain: "고령산",
    region: "수도권",
    address: "경기도 파주시 광탄면 보광로474번길 87",
    note: "영조의 사모곡이 어신각에 깃든 고령산 자락의 절.",
    lat: 37.753,
    lng: 126.9196,
    templestay: true,
  },
  {
    name: "용궁사",
    hanja: "龍宮寺",
    mountain: "백운산",
    region: "수도권",
    address: "인천광역시 중구 운남로 199-1",
    note: "천삼백 년 느티나무가 산문을 지키는 영종도의 옛 절.",
    lat: 37.4972,
    lng: 126.5278,
  },
  // ── 강원 · 2차 보강 ──
  {
    name: "수타사",
    hanja: "壽陀寺",
    mountain: "공작산",
    region: "강원",
    address: "강원특별자치도 홍천군 영귀미면 수타사로 473",
    note: "공작산 물소리 곁에서 월인석보를 지켜온 천년 고찰.",
    lat: 37.6985,
    lng: 127.9594,
  },
  {
    name: "도피안사",
    hanja: "到彼岸寺",
    mountain: "화개산",
    region: "강원",
    address: "강원특별자치도 철원군 동송읍 도피동길 23",
    note: "철원 들녘 끝, 천 년 철불이 고요히 앉은 피안의 절.",
    lat: 38.2401,
    lng: 127.2181,
  },
  {
    name: "등명낙가사",
    hanja: "燈明洛伽寺",
    mountain: "괘방산",
    region: "강원",
    address: "강원특별자치도 강릉시 강동면 괘방산길 16",
    note: "정동진 바다가 마당처럼 내려다보이는 괘방산 중턱의 절.",
    lat: 37.7114,
    lng: 129.0064,
    templestay: true,
  },
  {
    name: "휴휴암",
    hanja: "休休庵",
    mountain: "동해 바닷가",
    region: "강원",
    address: "강원특별자치도 양양군 현남면 광진2길 3-16",
    note: "파도 소리에 번뇌를 내려놓는, 쉬고 또 쉬는 바닷가 암자.",
    lat: 37.9612,
    lng: 128.7676,
  },
  {
    name: "천은사",
    hanja: "天恩寺",
    mountain: "두타산",
    region: "강원",
    address: "강원특별자치도 삼척시 미로면 동안로 816",
    note: "이승휴가 제왕운기를 써 내려간 두타산 깊은 골의 절.",
    lat: 37.4447,
    lng: 129.0427,
  },
  {
    name: "보현사",
    hanja: "普賢寺",
    mountain: "보현산",
    region: "강원",
    address: "강원특별자치도 강릉시 성산면 보현길 396",
    note: "대관령 아랫자락, 천년 솔숲에 안긴 고요한 선원.",
    lat: 37.7369,
    lng: 128.7695,
    templestay: true,
  },
  {
    name: "화암사",
    hanja: "禾巖寺",
    mountain: "금강산",
    region: "강원",
    address: "강원특별자치도 고성군 토성면 화암사길 100",
    note: "금강산 남쪽 첫 봉우리, 수바위 아래 안긴 절.",
    lat: 38.2268,
    lng: 128.4692,
    templestay: true,
  },
  {
    name: "심원사",
    hanja: "深源寺",
    mountain: "보개산",
    region: "강원",
    address: "강원특별자치도 철원군 동송읍 상노1길 58",
    note: "땅에서 솟은 지장보살을 모신, 기도 영험 제일의 도량.",
    lat: 38.1632,
    lng: 127.2494,
    templestay: true,
  },
  // ── 충청 · 2차 보강 ──
  {
    name: "부석사",
    hanja: "浮石寺",
    mountain: "도비산",
    region: "충청",
    address: "충청남도 서산시 부석면 부석사길 243",
    note: "도비산 중턱, 서해 낙조가 마당까지 밀려드는 천년 고찰.",
    lat: 36.7039,
    lng: 126.4122,
    templestay: true,
  },
  {
    name: "각원사",
    hanja: "覺願寺",
    mountain: "태조산",
    region: "충청",
    address: "충청남도 천안시 동남구 각원사길 245",
    note: "태조산 자락, 남북통일을 발원하는 청동대불이 앉은 절.",
    lat: 36.8345,
    lng: 127.1965,
  },
  {
    name: "광덕사",
    hanja: "廣德寺",
    mountain: "광덕산",
    region: "충청",
    address: "충청남도 천안시 동남구 광덕면 광덕사길 30",
    note: "이 땅의 호두나무가 처음 뿌리내린 광덕산 품속의 고찰.",
    lat: 36.6759,
    lng: 127.0424,
  },
  {
    name: "고란사",
    hanja: "皐蘭寺",
    mountain: "부소산",
    region: "충청",
    address: "충청남도 부여군 부여읍 부소로 1-25",
    note: "낙화암 벼랑 아래, 백마강을 굽어보는 백제의 옛 절.",
    lat: 36.2926,
    lng: 126.9132,
  },
  {
    name: "보탑사",
    hanja: "寶塔寺",
    mountain: "보련산",
    region: "충청",
    address: "충청북도 진천군 진천읍 김유신길 641",
    note: "못 하나 쓰지 않고 올린 삼층목탑이 연꽃 골짜기에 솟은 절.",
    lat: 36.8396,
    lng: 127.341,
  },
  {
    name: "영국사",
    hanja: "寧國寺",
    mountain: "천태산",
    region: "충청",
    address: "충청북도 영동군 양산면 영국동길 225-35",
    note: "천 년 은행나무가 가을마다 온 절을 금빛으로 물들이는 곳.",
    lat: 36.1581,
    lng: 127.6105,
    templestay: true,
  },
  {
    name: "반야사",
    hanja: "般若寺",
    mountain: "백화산",
    region: "충청",
    address: "충청북도 영동군 황간면 백화산로 652",
    note: "호랑이 형상의 돌너덜 아래, 배롱나무 붉게 피는 문수 기도처.",
    lat: 36.2806,
    lng: 127.9093,
    templestay: true,
  },
  {
    name: "정방사",
    hanja: "淨芳寺",
    mountain: "금수산",
    region: "충청",
    address: "충청북도 제천시 수산면 옥순봉로12길 165",
    note: "금수산 절벽에 처마를 기대고 청풍호를 내려다보는 암자.",
    lat: 36.9989,
    lng: 128.2077,
  },
  {
    name: "석종사",
    hanja: "釋宗寺",
    mountain: "금봉산",
    region: "충청",
    address: "충청북도 충주시 직동길 271-56",
    note: "폐사지 위에 다시 일어선, 참선의 기풍이 서린 금봉산 선원.",
    lat: 36.9487,
    lng: 127.9696,
    templestay: true,
  },
  {
    name: "영평사",
    hanja: "永平寺",
    mountain: "장군산",
    region: "충청",
    address: "세종특별자치시 장군면 영평사길 124",
    note: "가을이면 구절초가 온 산을 하얗게 물들이는 절.",
    lat: 36.4732,
    lng: 127.2278,
    templestay: true,
  },
  // ── 영남 · 2차 보강 ──
  {
    name: "선본사",
    hanja: "禪本寺",
    mountain: "팔공산",
    region: "영남",
    address: "경상북도 경산시 와촌면 갓바위로 699",
    note: "한 가지 소원은 꼭 들어준다는 갓바위 부처님의 기도처.",
    lat: 35.9869,
    lng: 128.7393,
    templestay: true,
  },
  {
    name: "파계사",
    hanja: "把溪寺",
    mountain: "팔공산",
    region: "영남",
    address: "대구광역시 동구 파계로 741",
    note: "아홉 갈래 계곡물을 끌어안은, 영조 임금 설화가 서린 절.",
    lat: 36.0017,
    lng: 128.64,
  },
  {
    name: "해동용궁사",
    hanja: "海東龍宮寺",
    mountain: "바닷가 절벽",
    region: "영남",
    address: "부산광역시 기장군 기장읍 용궁길 86",
    note: "파도 소리가 목탁을 대신하는 바닷가 절벽의 절.",
    lat: 35.1883,
    lng: 129.2233,
  },
  {
    name: "오어사",
    hanja: "吾魚寺",
    mountain: "운제산",
    region: "영남",
    address: "경상북도 포항시 남구 오천읍 오어로 1",
    note: "원효와 혜공의 설화가 어린, 호수를 품은 절.",
    lat: 35.9263,
    lng: 129.3689,
  },
  {
    name: "청량사",
    hanja: "淸凉寺",
    mountain: "청량산",
    region: "영남",
    address: "경상북도 봉화군 명호면 청량산길 199-152",
    note: "열두 암봉 한가운데, 공민왕 친필 현판이 걸린 절.",
    lat: 36.789,
    lng: 128.9193,
    templestay: true,
  },
  {
    name: "불영사",
    hanja: "佛影寺",
    mountain: "천축산",
    region: "영남",
    address: "경상북도 울진군 금강송면 불영사길 48",
    note: "연못에 부처 그림자가 비친다는 금강송 숲속 비구니 도량.",
    lat: 36.9408,
    lng: 129.2738,
  },
  {
    name: "대전사",
    hanja: "大典寺",
    mountain: "주왕산",
    region: "영남",
    address: "경상북도 청송군 주왕산면 공원길 226",
    note: "기암 병풍을 등에 지고 주왕산 골짜기를 여는 절.",
    lat: 36.3969,
    lng: 129.1454,
  },
  {
    name: "관룡사",
    hanja: "觀龍寺",
    mountain: "화왕산",
    region: "영남",
    address: "경상남도 창녕군 창녕읍 화왕산관룡사길 171",
    note: "용선대 돌부처가 억새 능선을 내려다보는 절.",
    lat: 35.5319,
    lng: 128.5533,
  },
  {
    name: "칠불사",
    hanja: "七佛寺",
    mountain: "지리산",
    region: "영남",
    address: "경상남도 하동군 화개면 범왕길 528",
    note: "가야 일곱 왕자가 성불했다는 지리산 깊은 골의 절.",
    lat: 35.2822,
    lng: 127.6093,
  },
  {
    name: "대원사",
    hanja: "大源寺",
    mountain: "지리산",
    region: "영남",
    address: "경상남도 산청군 삼장면 대원사길 455",
    note: "천왕봉 가는 길목, 계곡 물소리 깊은 비구니 참선도량.",
    lat: 35.355,
    lng: 127.8069,
    templestay: true,
  },
  // ── 호남 · 2차 보강 ──
  {
    name: "보림사",
    hanja: "寶林寺",
    mountain: "가지산",
    region: "호남",
    address: "전남 장흥군 유치면 보림사로 224",
    note: "구산선문 가운데 가장 먼저 열린 가지산문, 철불이 천 년을 앉아 있는 절.",
    lat: 34.8078,
    lng: 126.8967,
    templestay: true,
  },
  {
    name: "태안사",
    hanja: "泰安寺",
    mountain: "동리산",
    region: "호남",
    address: "전남 곡성군 죽곡면 태안로 622-215",
    note: "물소리 위 능파각을 건너면 비로소 열리는 동리산의 옛 절.",
    lat: 35.1317,
    lng: 127.3869,
    templestay: true,
  },
  {
    name: "백련사",
    hanja: "白蓮寺",
    mountain: "만덕산",
    region: "호남",
    address: "전남 강진군 도암면 백련사길 145",
    note: "동백숲 그늘을 지나 다산초당으로 이어지는 남도의 옛 절.",
    lat: 34.5878,
    lng: 126.7477,
    templestay: true,
  },
  {
    name: "흥국사",
    hanja: "興國寺",
    mountain: "영취산",
    region: "호남",
    address: "전남 여수시 흥국사길 160",
    note: "봄마다 영취산 진달래가 붉게 번지는, 의승수군이 지킨 절.",
    lat: 34.8214,
    lng: 127.7003,
    templestay: true,
  },
  {
    name: "증심사",
    hanja: "證心寺",
    mountain: "무등산",
    region: "호남",
    address: "광주 동구 증심사길 177",
    note: "무등산 자락에 안겨 광주를 굽어보는 천년 도량.",
    lat: 35.1288,
    lng: 126.9695,
    templestay: true,
  },
  {
    name: "쌍봉사",
    hanja: "雙峯寺",
    mountain: "사자산",
    region: "호남",
    address: "전남 화순군 이양면 쌍산의로 459",
    note: "목탑처럼 세 층으로 솟은 대웅전, 국보 철감선사탑이 지키는 절.",
    lat: 34.8872,
    lng: 127.06,
    templestay: true,
  },
  {
    name: "사성암",
    hanja: "四聖庵",
    mountain: "오산",
    region: "호남",
    address: "전남 구례군 문척면 사성암길 303",
    note: "오산 벼랑 끝에 매달려 섬진강을 굽어보는 기도처.",
    lat: 35.18,
    lng: 127.4807,
    templestay: true,
  },
  {
    name: "탑사",
    hanja: "塔寺",
    mountain: "마이산",
    region: "호남",
    address: "전북 진안군 마령면 마이산남로 367",
    note: "말 귀를 닮은 두 봉우리 아래 돌탑 팔십여 기가 하늘로 솟은 절.",
    lat: 35.7586,
    lng: 127.4116,
  },
  {
    name: "개암사",
    hanja: "開巖寺",
    mountain: "능가산",
    region: "호남",
    address: "전북 부안군 상서면 개암로 248",
    note: "우금바위를 등에 지고 단정히 앉은 백제의 옛 절.",
    lat: 35.6626,
    lng: 126.6495,
    templestay: true,
  },
  {
    name: "화암사",
    hanja: "花巖寺",
    mountain: "불명산",
    region: "호남",
    address: "전북 완주군 경천면 화암사길 271",
    note: "시인이 '잘 늙은 절'이라 불렀던 불명산 숲속의 국보 극락전.",
    lat: 36.0662,
    lng: 127.287,
  },
  // ── 제주 · 2차 보강 ──
  {
    name: "불탑사",
    hanja: "佛塔寺",
    mountain: "원당봉",
    region: "제주",
    address: "제주특별자치도 제주시 원당로16길 41",
    note: "검은 현무암으로 쌓은 보물 오층석탑이 칠백 년을 지켜온 원당봉 기슭의 절.",
    lat: 33.529,
    lng: 126.5982,
  },
  {
    name: "천왕사",
    hanja: "天王寺",
    mountain: "한라산",
    region: "제주",
    address: "제주특별자치도 제주시 1100로 2528-111",
    note: "아흔아홉 골짜기 깊은 곳, 기암 병풍 아래 들어앉은 기도처.",
    lat: 33.4076,
    lng: 126.4949,
  },
  {
    name: "선덕사",
    hanja: "善德寺",
    mountain: "한라산",
    region: "제주",
    address: "제주특별자치도 서귀포시 516로771번길 64",
    note: "한라산 남녘 효돈천 물소리 곁에 앉은 법화의 도량.",
    lat: 33.3205,
    lng: 126.5936,
  },
  {
    name: "존자암",
    hanja: "尊者庵",
    mountain: "볼레오름",
    region: "제주",
    address: "제주특별자치도 서귀포시 영실로 226",
    note: "해발 천이백 미터 영실 숲속, 제주 불교가 처음 깃든 가장 오래된 암자.",
    lat: 33.3477,
    lng: 126.482,
  },
  {
    name: "금룡사",
    hanja: "金龍寺",
    mountain: "김녕 바닷가",
    region: "제주",
    address: "제주특별자치도 제주시 구좌읍 김녕로 148-11",
    note: "파도 소리를 목탁 삼아 김녕 바다를 마주 앉은 해변 도량.",
    lat: 33.5539,
    lng: 126.7536,
    templestay: true,
  },
  {
    name: "기원정사",
    mountain: "마라도",
    region: "제주",
    address: "제주특별자치도 서귀포시 대정읍 마라로 87",
    note: "국토 최남단 마라도, 북녘을 바라보는 해수관음의 절.",
    lat: 33.116,
    lng: 126.2666,
  },
];

// 카카오맵 이름 검색 링크 — API 키가 필요 없는 공식 링크 방식
export function kakaoMapUrl(name: string): string {
  return `https://map.kakao.com/link/search/${encodeURIComponent(name)}`;
}
